import streamlit as st
import google.generativeai as genai
import json
from PIL import Image
import io

# --- TEMA AYARLARI ---
st.set_page_config(page_title="Cine Lab: Production Factory", layout="wide")

# Cine Lab Tema Renkleri
is_light_mode = st.sidebar.toggle("Light Mode", value=False)
if is_light_mode:
    main_bg, main_txt, header_col, card_bg, border_col = "#F9FEFF", "#222121", "#F7BE14", "#FFFFFF", "#E0E0E0"
else:
    main_bg, main_txt, header_col, card_bg, border_col = "#222121", "#F9FEFF", "#CCD4D7", "#161b22", "#30363d"

# Custom CSS
st.markdown(f"""
    <style>
    .stApp {{ background-color: {main_bg}; color: {main_txt}; }}
    .stTextArea textarea {{ background-color: {card_bg}; color: {main_txt}; border: 1px solid {border_col}; border-radius: 10px; }}
    h1, h2, h3 {{ color: {header_col}; font-family: 'Inter', sans-serif; }}
    .stButton button {{ background-color: {header_col}; color: {main_bg}; border-radius: 20px; font-weight: bold; width: 100%; border: none; height: 3em; }}
    .stButton button:hover {{ background-color: {main_txt}; color: {main_bg}; }}
    </style>
    """, unsafe_allow_html=True)

# --- GÜVENLİ API BAĞLANTISI ---
try:
    # Secrets'tan çekiyoruz
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    model = genai.GenerativeModel('imagen-3') # Nano Banana / Imagen 3
except Exception as e:
    st.error("Secrets ayarlarında API Key bulunamadı veya hatalı.")

# --- ARAYÜZ TASARIMI ---
st.title("🎬 Cine Lab: Production Factory")
st.markdown("---")

col1, col2 = st.columns([1, 1.5], gap="large")

with col1:
    st.subheader("📋 JSON Recipe")
    json_input = st.text_area("Cine Lab'dan gelen promptu buraya yapıştır:", height=350)
    
    generate_btn = st.button("🚀 FABRİKAYI ÇALIŞTIR (GENERATE)")

with col2:
    st.subheader("🖼️ Production Output")
    
    if generate_btn and json_input:
        try:
            # JSON'u oku
            recipe = json.loads(json_input)
            
            # Fabrika mantığı: JSON'u teknik prompta çeviriyoruz
            # Burada 'recipe.get' kullanarak JSON içindeki anahtarları okuyoruz
            raw_prompt = f"Professional photography, style: {recipe.get('style', 'cinematic')}, " \
                         f"shot on {recipe.get('camera', 'High-end DSLR')}, " \
                         f"lens: {recipe.get('lens', '50mm prime')}, " \
                         f"lighting: {recipe.get('lighting', 'studio')}, " \
                         f"detail level: ultra-realistic, anti-plastic texture."

            with st.spinner("Nano Banana görseli işliyor..."):
                # Görsel oluşturma
                response = model.generate_content(raw_prompt)
                image = response.images[0]
                
                # Görseli göster
                st.image(image, use_container_width=True, caption="Generated by Nano Banana")
                
                # Kaydet butonu
                buf = io.BytesIO()
                image.save(buf, format="PNG")
                st.download_button(
                    label="💾 GÖRSELİ KAYDET",
                    data=buf.getvalue(),
                    file_name="factory_output.png",
                    mime="image/png"
                )
        except json.JSONDecodeError:
            st.warning("Lütfen geçerli bir JSON formatı yapıştırın.")
        except Exception as e:
            st.error(f"Üretim bandında hata oluştu: {e}")
    else:
        # Boş durum tasarımı
        st.info("Reçete bekleniyor... Üretim bandı hazır.")
